name: start_project_blog_g1
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # add this line
    sdk: flutter         # add this line
  flutter_bloc: ^7.1.0
  google_fonts: ^2.1.0
  material_floating_search_bar: ^0.3.7
  flutter_secure_storage: ^4.2.1
  equatable: ^2.0.3
  shared_preferences: ^2.0.7
  flutter_svg: ^0.22.0
  readmore: ^2.1.0
  carousel_slider: ^4.0.0
  http: 
  google_sign_in: ^5.1.0
  google_sign_in_web: ^0.10.0+2
  cupertino_icons: ^1.0.2
  firebase_auth: ^3.1.0
  jwt_decode: ^0.3.1
  otp_text_field: ^1.1.1
  geolocator: ^7.7.0
  flutter_otp_text_field: ^1.0.0
  get_it: ^7.2.0
  url_launcher: 
  flutter_rating_bar: ^4.0.0
  google_maps_flutter: ^2.1.4
  flutter_staggered_grid_view: ^0.6.1
  timeago: ^3.2.2
  skeleton_text: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.1
  mockito: ^5.0.14
  mocktail:
  bloc_test: ^8.1.0
flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: Poppins Regular
      fonts:
        - asset: fonts/Poppins-Regular.ttf
          weight: 400
    - family: Poppins Italic
      fonts:
        - asset: fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
    - family: Poppins Black
      fonts:
        - asset: fonts/Poppins-Black.ttf
          weight: 900
    - family: Poppins Black Italic
      fonts:
        - asset: fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic
    - family: Poppins Bold
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700
    - family: Poppins Bold Italic
      fonts:
        - asset: fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
    - family: Poppins ExtraBold
      fonts:
        - asset: fonts/Poppins-ExtraBold.ttf
          weight: 800
    - family: Poppins ExtraBold Italic
      fonts:
        - asset: fonts/Poppins-ExtraBoldItalic.ttf
          weight: 800
          style: italic
    - family: Poppins ExtraLight
      fonts:
        - asset: fonts/Poppins-ExtraLight.ttf
          weight: 200
    - family: Poppins ExtraLight Italic
      fonts:
        - asset: fonts/Poppins-ExtraLightItalic.ttf
          weight: 200
          style: italic
    - family: Poppins Light
      fonts:
        - asset: fonts/Poppins-Light.ttf
          weight: 300
    - family: Poppins Light Italic
      fonts:
        - asset: fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
    - family: Poppins Medium
      fonts:
        - asset: fonts/Poppins-Medium.ttf
          weight: 500
    - family: Poppins Medium Italic
      fonts:
        - asset: fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
    - family: Poppins SemiBold
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf
          weight: 600
    - family: Poppins SemiBold Italic
      fonts:
        - asset: fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
    - family: Poppins Thin
      fonts:
        - asset: fonts/Poppins-Thin.ttf
          weight: 100
    - family: Poppins Thin Italic
      fonts:
        - asset: fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic      
  assets:
    - assets/

